---
deployment:
  tasks:
    - /home/c7v64szlhjqa/nodevenv/phugialand-app/22/bin/npm ci --omit=optional --prefix /home/c7v64szlhjqa/phugialand-app
    - /usr/bin/mkdir -p /home/c7v64szlhjqa/phugialand-app/tmp
    - /usr/bin/touch /home/c7v64szlhjqa/phugialand-app/tmp/restart.txt